### ISSUE TITLE
Archivo dll

### ISSUE THREAD

**Issue by LuisFerP** [sap-archive/lumira-extension-da-sql-server-analysis-services-ssas#1]
Buen dia una consulta, es que eh estado buscando el interop.ADOMB.dll pero no aparece por ningún lado, me podría indicar donde puedo conseguirlo o si me puede enviar a mi correo dicho archivo

**Comment by AnnieMT** [comment]
Hola @LuisFerP 

Por razones legales , no compartimos los archivos DLL en GitHub . Como usted sabe , los archivos DLL pueden causar problemas en el sistema en Windows y que vayan a ser descargado y utilizado " bajo su propio riesgo ". No proporcionamos estos archivos , y otra vez por razones legales no podemos apuntar a donde se puede descargar desde , aunque se puede hacer su propia búsqueda en Internet (de nuevo , a su propio riesgo ).

Gracias,
- Annie
