### ISSUE TITLE
.dll files

### ISSUE THREAD

**Issue by mynorm** [sap-archive/lumira-extension-da-sql-server-analysis-services-ssas#2]
Hi.

I was looking for the 2 dll files but I was unable to find them. ¿Could you please tell me where do I find them? I already look in my server to some versions of the two of them, but i can not find the exact "Interop.%" .

**Comment by AnnieMT** [comment]
Hi @mynorm 

For legal reasons, we do not share the DLL files on GitHub. As you may know, DLL files may cause system issues on Windows and they are to be downloaded and used "AT YOUR OWN RISK". We do not provide these files, and again for legal reasons we cannot point you to where you can download them from, although you can do your own internet search (again, at your own risk).
