### ISSUE TITLE
unable to download the dll file Interop.ADOMD.dll required for the extention. 

### ISSUE THREAD

**Issue by abinjacob** [sap-archive/lumira-extension-da-sql-server-analysis-services-ssas#4]
Need help to download Interop.ADOMD.dll
tried installing MS feature pack ADOMD.NET ,But could not find the dll.
Please help.

Thanks,
Abin

**Comment by AnnieMT** [comment]
Hi @abinjacob 

Legally, we cannot provide DLL files since they don't come with support. They are a "find-and-use-at-your-own-risk" component which we cannot help with.

Thanks!
